export const PHONE1='+237 681 232 399', PHONE2='+237 659 48 34 26'
export const WA='237659483426', EMAIL='heartmetarllugical@gmail.com'
export const TIKTOK='https://www.tiktok.com/@le.btisseur34?_r=1&_t=ZS-9A8vwmzmtWc'
export const FACEBOOK='https://www.facebook.com/share/1CLtGfuDuc/'
export const wa=(msg)=>`https://wa.me/${WA}?text=${encodeURIComponent(msg)}`
const A=(f)=>`/assets/${f}.webp`
export const activities=[
 {slug:'soudure',img:A('soudure-grille'),gallery:['soudure-atelier','soudure-grille','garde-corps','escalier'].map(A),
  fr:{title:'Soudure',desc:'Travaux de soudure métallique réalisés avec précision, du portail à l’escalier.',services:['Portails et portes métalliques','Garde-corps','Escaliers métalliques','Grilles et structures']},
  en:{title:'Welding',desc:'Metal welding work carried out with precision, from gates to staircases.',services:['Metal gates and doors','Railings','Metal staircases','Grilles and frames']}},
 {slug:'menuiserie-aluminium',img:A('alu-facade-vitree'),gallery:['alu-facade-vitree','alu-ascenseur-1','alu-ascenseur-2','alu-verre-arches','alu-portes-chantier','alu-cloison','alu-fenetres','alu-fenetre','alu-decoupe'].map(A),
  fr:{title:'Menuiserie aluminium',desc:'Fenêtres, portes, cloisons, façades vitrées et ouvrages en aluminium.',services:['Fenêtres coulissantes','Portes vitrées','Cloisons vitrées','Façades vitrées','Cages d’ascenseur vitrées','Garde-corps en verre']},
  en:{title:'Aluminium joinery',desc:'Windows, doors, partitions, glazed facades and aluminium fittings.',services:['Sliding windows','Glazed doors','Glass partitions','Glazed facades','Glazed lift shafts','Glass balustrades']}},
 {slug:'menuiserie-metallique',img:A('portail'),gallery:['portail','inox-garde-corps','metal-cloture','garde-corps','escalier'].map(A),
  fr:{title:'Menuiserie métallique',desc:'Portes, portails, clôtures et garde-corps métalliques ou inox.',services:['Portes et portails','Garde-corps métal et inox','Clôtures','Escaliers']},
  en:{title:'Metal joinery',desc:'Metal and stainless steel doors, gates, fences and railings.',services:['Doors and gates','Metal and stainless railings','Fences','Staircases']}},
 {slug:'resine-epoxy',img:A('epoxy-3d-1'),gallery:['epoxy-3d-1','epoxy-3d-2','epoxy-pose','epoxy-equipe'].map(A),
  fr:{title:'Résine époxy',desc:'Sols en résine époxy, dont des décors 3D à finition brillante.',services:['Sols décoratifs 3D','Sols en résine époxy']},
  en:{title:'Epoxy resin',desc:'Epoxy resin floors, including glossy 3D designs.',services:['3D decorative floors','Epoxy resin floors']}},
 {slug:'peinture',img:A('peinture-facade'),gallery:['peinture-facade'].map(A),
  fr:{title:'Peinture',desc:'Travaux de peinture et de finition.',services:['Peinture de façades']},
  en:{title:'Painting',desc:'Painting and finishing work.',services:['Facade painting']}},
 {slug:'plafonds-suspendus',img:A('plafond-moulure'),gallery:['plafond-moulure'].map(A),
  fr:{title:'Plafonds suspendus',desc:'Pose de plafonds avec moulures et éclairage intégré.',services:['Plafonds à moulures','Éclairage encastré']},
  en:{title:'Suspended ceilings',desc:'Ceilings with mouldings and recessed lighting.',services:['Moulded ceilings','Recessed lighting']}},
 {slug:'carrelage',img:A('carrelage-sanitaires'),gallery:['carrelage-sanitaires'].map(A),
  fr:{title:'Carrelage',desc:'Travaux de carrelage.',services:['Carrelage de sanitaires']},
  en:{title:'Tiling',desc:'Tiling work.',services:['Bathroom tiling']}},
 {slug:'revetement-mural',img:A('placo-mur-tv'),gallery:['placo-mur-tv'].map(A),
  fr:{title:'Revêtement mural',desc:'Habillages muraux et finitions.',services:['Habillage mural sur ossature']},
  en:{title:'Wall covering',desc:'Wall cladding and finishes.',services:['Framed wall cladding']}},
 {slug:'plomberie',img:A('plomberie-nourrice-1'),gallery:['plomberie-nourrice-1','plomberie-nourrice-2','plomberie-tuyaux','plomberie-sanitaire'].map(A),
  fr:{title:'Plomberie',desc:'Réseaux d’eau et installation sanitaire.',services:['Réseaux d’alimentation avec nourrice','Installation sanitaire']},
  en:{title:'Plumbing',desc:'Water networks and sanitary installation.',services:['Supply networks with manifold','Sanitary installation']}},
 {slug:'construction',img:A('construction-gros-oeuvre'),gallery:['construction-gros-oeuvre','construction-echafaudage'].map(A),
  fr:{title:'Construction',desc:'Chantiers de bâtiment et gros œuvre.',services:['Gros œuvre','Chantiers de bâtiment']},
  en:{title:'Construction',desc:'Building sites and structural work.',services:['Structural work','Building sites']}}
]
export const formations=[
 {slug:'soudure',img:A('soudure-atelier'),fr:'Soudure',en:'Welding'},
 {slug:'aluminium',img:A('alu-fenetres'),fr:'Aluminium',en:'Aluminium'},
 {slug:'resine-epoxy',img:A('epoxy-3d-2'),fr:'Résine époxy',en:'Epoxy resin'}]
export const heroSlides=[A('soudure-grille'),A('epoxy-3d-1'),A('alu-cloison'),A('garde-corps')]
export const T={
fr:{nav:['Accueil','À propos','Activités','Réalisations','HMA Academic','Contact'],
 tag:'BTP · Travaux métalliques · Finitions',
 heroP:'Entreprise basée à Yaoundé, spécialisée dans le BTP, les travaux métalliques et les finitions : soudure, aluminium, résine époxy, peinture, carrelage, plomberie.',
 c1:'Découvrir nos activités',c2:'Voir nos réalisations',c3:'Nous contacter',hma:'HMA Academic',
 aboutT:'Qui sommes-nous',aboutP:'Heart Metallurgical Construction (HMC SARL) est une entreprise du BTP installée à Yaoundé, à environ 500 mètres de Cimencam, côté Nomayos. Elle intervient en travaux métalliques, menuiserie et finitions. Responsable : Pamel Nanfack.',
 actT:'Nos activités',actS:'Choisissez un domaine pour voir les prestations et les réalisations.',
 realT:'Nos réalisations',realS:'Photos de chantiers et d’ateliers HMC.',
 soon:'Photos bientôt disponibles. Contactez-nous pour en savoir plus.',
 services:'Prestations',other:'Autres activités',gal:'Réalisations',
 hmaT:'HMA — Heart Metallurgical Academic',hmaP:'La branche de formation professionnelle de HMC. Formations en présentiel, dans l’atelier, avec certification délivrée à la fin de la formation.',
 hmaF:'Formations',hmaHow:'Comment ça marche',hmaL:['En présentiel','Dans l’atelier','Certification délivrée à la fin de la formation'],
 hmaInfo:'Prix, durées, dates et conditions d’inscription : demandez-les directement à HMA sur WhatsApp.',hmaCta:'Demander les détails',
 contactT:'Contact',contactP:'Le plus simple : appelez-nous ou écrivez-nous sur WhatsApp.',call:'Appeler',mail:'Email',
 install:'Installer l’App',loc:'Yaoundé, à environ 500 m de Cimencam, côté Nomayos',
 waHMC:(d)=>`Bonjour HMC, je souhaite obtenir des informations concernant votre service de ${d}.`,
 waHMA:(d)=>`Bonjour HMA, je souhaite obtenir des informations concernant la formation en ${d}.`,
 waGen:'Bonjour HMC, je souhaite obtenir des informations.',
 view:'Voir',close:'Fermer',menu:'Menu',all:'Tout'},
en:{nav:['Home','About','Activities','Projects','HMA Academic','Contact'],
 tag:'Construction · Metalwork · Finishing',
 heroP:'Yaoundé-based company specialised in construction, metalwork and finishing: welding, aluminium, epoxy resin, painting, tiling, plumbing.',
 c1:'Discover our activities',c2:'See our projects',c3:'Contact us',hma:'HMA Academic',
 aboutT:'Who we are',aboutP:'Heart Metallurgical Construction (HMC SARL) is a construction company based in Yaoundé, about 500 metres from Cimencam, Nomayos side. It works in metalwork, joinery and finishing. Manager: Pamel Nanfack.',
 actT:'Our activities',actS:'Pick a field to see services and projects.',
 realT:'Our projects',realS:'Photos from HMC sites and workshop.',
 soon:'Photos coming soon. Contact us to learn more.',
 services:'Services',other:'Other activities',gal:'Projects',
 hmaT:'HMA — Heart Metallurgical Academic',hmaP:'The professional training branch of HMC. In-person courses in the workshop, with a certificate awarded at the end.',
 hmaF:'Courses',hmaHow:'How it works',hmaL:['In person','In the workshop','Certificate awarded at the end of the course'],
 hmaInfo:'Prices, duration, dates and enrolment conditions: ask HMA directly on WhatsApp.',hmaCta:'Ask for details',
 contactT:'Contact',contactP:'Simplest way: call us or message us on WhatsApp.',call:'Call',mail:'Email',
 install:'Install the app',loc:'Yaoundé, about 500 m from Cimencam, Nomayos side',
 waHMC:(d)=>`Hello HMC, I would like information about your ${d} service.`,
 waHMA:(d)=>`Hello HMA, I would like information about the ${d} course.`,
 waGen:'Hello HMC, I would like some information.',
 view:'View',close:'Close',menu:'Menu',all:'All'}}
